#pragma once

#include <stddef.h>
#include <stdint.h>

typedef struct {
    uint16_t start;
    uint16_t count;
    uint8_t frameOrder;
    uint8_t functionCode;
} voltronic_modbus_poll_block_t;

#define VOLTRONIC_MODBUS_DEFAULT_SLAVE_ADDR 0x01u

#define VOLTRONIC_MB_FRAME_CLASSIC        0u
#define VOLTRONIC_MB_FRAME_FUNCTION_FIRST 1u

#define VOLTRONIC_MB_READ_HOLDING_REGS    0x03u
#define VOLTRONIC_MB_READ_INPUT_REGS      0x04u

/* Voltronic Power "Inverter and BMS 485 communication Protocol", 2020-03-25. */
#define VOLTRONIC_MB_REG_VERSION_START        0x0001u
#define VOLTRONIC_MB_REG_PROTOCOL_TYPE        0x0001u
#define VOLTRONIC_MB_REG_PROTOCOL_VERSION     0x0002u

#define VOLTRONIC_MB_REG_STATUS_START         0x0010u
#define VOLTRONIC_MB_REG_CELL_COUNT           0x0010u
#define VOLTRONIC_MB_REG_CELL01               0x0011u
#define VOLTRONIC_MB_MAX_CELLS                20u
#define VOLTRONIC_MB_REG_CELL_LAST            0x0024u
#define VOLTRONIC_MB_REG_TEMP_COUNT           0x0025u
#define VOLTRONIC_MB_REG_TEMP01_DECIK         0x0026u
#define VOLTRONIC_MB_MAX_TEMPS                10u
#define VOLTRONIC_MB_REG_TEMP_LAST            0x002Fu
#define VOLTRONIC_MB_REG_CHARGE_CURRENT_DA    0x0030u
#define VOLTRONIC_MB_REG_DISCHARGE_CURRENT_DA 0x0031u
#define VOLTRONIC_MB_REG_MODULE_VOLTAGE_DV    0x0032u
#define VOLTRONIC_MB_REG_SOC_PCT              0x0033u
#define VOLTRONIC_MB_REG_TOTAL_CAPACITY_MAH   0x0034u

#define VOLTRONIC_MB_REG_MANUFACTURER_START   0x0036u
#define VOLTRONIC_MB_REG_PARALLEL_PACKS       0x0036u
#define VOLTRONIC_MB_REG_CHARGE_ALARM         0x0037u
#define VOLTRONIC_MB_REG_DISCHARGE_ALARM      0x0038u
#define VOLTRONIC_MB_REG_CHARGE_PROTECT       0x0039u
#define VOLTRONIC_MB_REG_CHARGE_PROTECT2      0x003Au
#define VOLTRONIC_MB_REG_DISCHARGE_PROTECT    0x003Bu
#define VOLTRONIC_MB_REG_DISCHARGE_PROTECT2   0x003Cu
#define VOLTRONIC_MB_REG_BMS_STATE            0x003Du
#define VOLTRONIC_MB_REG_DESIGN_CAPACITY_MAH  0x003Eu
#define VOLTRONIC_MB_REG_STATUS_END           0x003Fu

#define VOLTRONIC_MB_REG_WARNING_START        0x0040u
#define VOLTRONIC_MB_REG_WARNING_CELL_COUNT   0x0040u
#define VOLTRONIC_MB_REG_CELL_STATE_PAIR01    0x0041u
#define VOLTRONIC_MB_REG_CELL_STATE_PAIR_LAST 0x004Au
#define VOLTRONIC_MB_REG_WARNING_TEMP_COUNT   0x0050u
#define VOLTRONIC_MB_REG_TEMP_STATE_PAIR01    0x0051u
#define VOLTRONIC_MB_REG_TEMP_STATE_PAIR_LAST 0x0055u
#define VOLTRONIC_MB_REG_MODULE_CHG_V_STATE   0x0060u
#define VOLTRONIC_MB_REG_MODULE_DIS_V_STATE   0x0061u
#define VOLTRONIC_MB_REG_CELL_CHG_V_STATE     0x0062u
#define VOLTRONIC_MB_REG_CELL_DIS_V_STATE     0x0063u
#define VOLTRONIC_MB_REG_MODULE_CHG_I_STATE   0x0064u
#define VOLTRONIC_MB_REG_MODULE_DIS_I_STATE   0x0065u
#define VOLTRONIC_MB_REG_MODULE_CHG_T_STATE   0x0066u
#define VOLTRONIC_MB_REG_MODULE_DIS_T_STATE   0x0067u
#define VOLTRONIC_MB_REG_CELL_CHG_T_STATE     0x0068u
#define VOLTRONIC_MB_REG_CELL_DIS_T_STATE     0x0069u
#define VOLTRONIC_MB_REG_WARNING_END          0x0069u
#define VOLTRONIC_MB_MODULE_STATE_COUNT       10u

#define VOLTRONIC_MB_REG_LIMITS_START         0x0070u
#define VOLTRONIC_MB_REG_CHARGE_V_LIMIT_DV    0x0070u
#define VOLTRONIC_MB_REG_DISCHARGE_V_LIMIT_DV 0x0071u
#define VOLTRONIC_MB_REG_CHARGE_I_LIMIT_DA    0x0072u
#define VOLTRONIC_MB_REG_DISCHARGE_I_LIMIT_DA 0x0073u
#define VOLTRONIC_MB_REG_CHG_DSG_STATUS       0x0074u
#define VOLTRONIC_MB_REG_RUNTIME_EMPTY_MIN    0x0075u
#define VOLTRONIC_MB_REG_REMAIN_CAPACITY_MAH  0x0076u
#define VOLTRONIC_MB_REG_LIMITS_END           0x0077u

#define VOLTRONIC_MB_STATUS_CHARGE_ENABLE     0x0080u
#define VOLTRONIC_MB_STATUS_DISCHARGE_ENABLE  0x0040u
#define VOLTRONIC_MB_STATUS_CHARGE_NOW        0x0020u
#define VOLTRONIC_MB_STATUS_CHARGE_NOW2       0x0010u
#define VOLTRONIC_MB_STATUS_FULL_CHARGE_REQ   0x0008u

/*
 * Several public implementations name JK's universal Modbus runtime map
 * "VOLTRONIC_MODBUS" and poll these compact blocks. JK UART protocol 007
 * appears in the app as Voltronic, so keep this map as the first live probe.
 */
#define VOLTRONIC_JK_REG_STATUS_START         0x106Cu
#define VOLTRONIC_JK_REG_CELL_COUNT           0x106Cu
#define VOLTRONIC_JK_REG_CHARGE_MOS           0x106Du
#define VOLTRONIC_JK_REG_DISCHARGE_MOS        0x106Eu
#define VOLTRONIC_JK_REG_BALANCE_ACTIVE       0x106Fu
#define VOLTRONIC_JK_REG_RATED_CAPACITY_MAH   0x1070u

#define VOLTRONIC_JK_REG_CELL01_MV            0x1200u
#define VOLTRONIC_JK_REG_CELL_STEP            0x0002u
#define VOLTRONIC_JK_MAX_CELLS                20u
#define VOLTRONIC_JK_REG_CELL_AVG_MV          0x1244u
#define VOLTRONIC_JK_REG_CELL_DIFF_MV         0x1246u
#define VOLTRONIC_JK_REG_MAX_MIN_CELL_IDX     0x1248u

#define VOLTRONIC_JK_REG_MOS_TEMP_DECIC       0x128Au
#define VOLTRONIC_JK_REG_PACK_VOLTAGE_MV_U32  0x1290u
#define VOLTRONIC_JK_REG_PACK_VOLTAGE_CV      0x1290u
#define VOLTRONIC_JK_REG_PACK_POWER_MW_U32    0x1294u
#define VOLTRONIC_JK_REG_PACK_CURRENT_MA_I32  0x1298u
#define VOLTRONIC_JK_REG_TEMP1_DECIC          0x129Cu
#define VOLTRONIC_JK_REG_TEMP2_DECIC          0x129Eu
#define VOLTRONIC_JK_REG_ALARM_U32            0x12A0u
#define VOLTRONIC_JK_REG_BALANCE_SOC_U8X2     0x12A6u
#define VOLTRONIC_JK_REG_REMAIN_MAH_I32       0x12A8u
#define VOLTRONIC_JK_REG_FULL_MAH_U32         0x12ACu
#define VOLTRONIC_JK_REG_CYCLES_U32           0x12B0u
#define VOLTRONIC_JK_REG_SOH_PRECHARGE_U8X2   0x12B8u

extern const voltronic_modbus_poll_block_t g_voltronicModbusPollBlocks[];
extern const size_t g_voltronicModbusPollBlocksCount;
